trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout code from GitHub'
  inputs:
    repository: self
    persistCredentials: true

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
  inputs:
    versionSpec: '3.x'

- script: |
    pip install aws-sam-cli
  displayName: 'Install AWS SAM CLI'

- script: |
    sam build
  displayName: 'Build SAM application'

- script: |
    zip -r aws-sam.zip .aws-sam
  displayName: 'Zip the .aws-sam folder'

- task: Bash@3
  displayName: 'Upload Zip to Nexus'
  inputs:
    targetType: 'inline'
    script: |
      curl -v -u $(nexus.NEXUS_USER):$(nexus.NEXUS_PASS) \
      --upload-file aws-sam.zip \
      $(nexus.NEXUS_URL)/repository/buildartifacts/aws-sam.zip

- script: |
    mkdir -p output
  displayName: 'Create output folder'

- script: |
    curl -v -u $(nexus.NEXUS_USER):$(nexus.NEXUS_PASS) \
    -o output/aws-sam.zip \
    $(nexus.NEXUS_URL)/repository/buildartifacts/aws-sam.zip
  displayName: 'Download zip from Nexus'

- script: |
    unzip output/aws-sam.zip -d output
  displayName: 'Unzip the file into output folder'

- script: |
    aws configure set aws_access_key_id $(aws.AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(aws.AWS_SECRET_ACCESS_KEY)
    aws configure set default.region eu-north-1
  displayName: 'Configure AWS CLI'

- script: |
    sam deploy \
      --stack-name AJ-STK \
      --capabilities CAPABILITY_IAM \
      --region eu-north-1 \
      --no-confirm-changeset \
      --resolve-s3
  displayName: 'Deploy SAM application'
